package com.aidocumenthelper.app

import android.app.Activity
import android.content.ContentValues
import android.content.Intent
import android.os.Build
import android.os.Environment
import android.provider.MediaStore
import android.util.Base64
import android.util.Log
import android.webkit.JavascriptInterface
import android.webkit.WebView
import android.widget.Toast
import androidx.core.content.FileProvider
import java.io.File
import java.util.concurrent.CountDownLatch
import java.util.concurrent.TimeUnit
import java.util.concurrent.atomic.AtomicBoolean

/**
 * Saves files generated by the web app (PDF, text, images).
 *
 * Android WebView cannot download blob: URLs, so the web app passes the
 * file contents here. On Android 10+ files are written to the public
 * Downloads folder through MediaStore (no storage permission needed).
 * On older versions the file is written to app cache and the system
 * share sheet is opened so the user can choose where to save it.
 */
class FileSaveBridge(
    private val activity: Activity,
    private val webView: WebView
) {

    private val tag = "FileSaveBridge"

    // Base64 payload limit (about 37 MB decoded).
    private val maxBase64Length = 50 * 1024 * 1024

    private val allowedMimeTypes = setOf(
        "application/pdf",
        "text/plain",
        "image/jpeg",
        "image/png",
        "image/webp"
    )

    @JavascriptInterface
    fun saveFile(
        base64Data: String?,
        fileName: String?,
        mimeType: String?
    ): String {
        if (!isCalledFromTrustedPage()) {
            Log.w(tag, "Refusing file save from untrusted page")
            return "error"
        }

        if (base64Data.isNullOrEmpty() || base64Data.length > maxBase64Length) {
            showToast("File is too large or empty.")
            return "error"
        }

        val baseMime = (mimeType ?: "")
            .substringBefore(';')
            .trim()
            .lowercase()

        val safeMime =
            if (baseMime in allowedMimeTypes) baseMime else "application/octet-stream"

        val safeName = sanitizeFileName(fileName, safeMime)

        val bytes = try {
            Base64.decode(base64Data, Base64.DEFAULT)
        } catch (e: IllegalArgumentException) {
            Log.e(tag, "Invalid file data", e)
            showToast("Could not save the file.")
            return "error"
        }

        return try {
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
                saveToDownloads(bytes, safeName, safeMime)
                showToast("Saved to Downloads: $safeName")
                "saved"
            } else {
                shareFromCache(bytes, safeName, safeMime)
                "shared"
            }
        } catch (e: Exception) {
            Log.e(tag, "Failed to save file", e)
            showToast("Could not save the file.")
            "error"
        }
    }

    private fun saveToDownloads(
        bytes: ByteArray,
        fileName: String,
        mimeType: String
    ) {
        val resolver = activity.contentResolver

        val values = ContentValues().apply {
            put(MediaStore.Downloads.DISPLAY_NAME, fileName)
            put(MediaStore.Downloads.MIME_TYPE, mimeType)
            put(MediaStore.Downloads.RELATIVE_PATH, Environment.DIRECTORY_DOWNLOADS)
            put(MediaStore.Downloads.IS_PENDING, 1)
        }

        val uri = resolver.insert(MediaStore.Downloads.EXTERNAL_CONTENT_URI, values)
            ?: throw IllegalStateException("Could not create download entry")

        try {
            resolver.openOutputStream(uri)?.use { output ->
                output.write(bytes)
            } ?: throw IllegalStateException("Could not open download for writing")

            values.clear()
            values.put(MediaStore.Downloads.IS_PENDING, 0)
            resolver.update(uri, values, null, null)
        } catch (e: Exception) {
            // Remove the incomplete entry instead of leaving a broken file.
            try {
                resolver.delete(uri, null, null)
            } catch (_: Exception) {
            }
            throw e
        }
    }

    private fun shareFromCache(
        bytes: ByteArray,
        fileName: String,
        mimeType: String
    ) {
        val dir = File(activity.cacheDir, "shared")

        if (!dir.exists() && !dir.mkdirs()) {
            throw IllegalStateException("Could not create share directory")
        }

        // Remove older shared copies so the cache does not grow.
        dir.listFiles()?.forEach { old ->
            if (System.currentTimeMillis() - old.lastModified() > 60 * 60 * 1000) {
                old.delete()
            }
        }

        val file = File(dir, fileName)
        file.writeBytes(bytes)

        val uri = FileProvider.getUriForFile(
            activity,
            "${activity.packageName}.fileprovider",
            file
        )

        val intent = Intent(Intent.ACTION_SEND).apply {
            type = mimeType
            putExtra(Intent.EXTRA_STREAM, uri)
            addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
        }

        activity.runOnUiThread {
            try {
                activity.startActivity(Intent.createChooser(intent, "Save or share $fileName"))
            } catch (e: Exception) {
                Log.e(tag, "No app available to save the file", e)
                Toast.makeText(activity, "No app available to save this file.", Toast.LENGTH_SHORT).show()
            }
        }
    }

    private fun sanitizeFileName(name: String?, mimeType: String): String {
        var cleaned = (name ?: "")
            .replace(Regex("[\\\\/:*?\"<>|\\p{Cntrl}]+"), "_")
            .trim()
            .trim('.')
            .take(120)

        if (cleaned.isBlank()) {
            cleaned = "document"
        }

        val extension = when (mimeType) {
            "application/pdf" -> ".pdf"
            "text/plain" -> ".txt"
            "image/jpeg" -> ".jpg"
            "image/png" -> ".png"
            "image/webp" -> ".webp"
            else -> ""
        }

        if (extension.isNotEmpty() && !cleaned.lowercase().endsWith(extension)) {
            cleaned += extension
        }

        return cleaned
    }

    // JavaScript interface methods run on a background thread; the
    // WebView URL must be read on the UI thread.
    private fun isCalledFromTrustedPage(): Boolean {
        val trusted = AtomicBoolean(false)
        val latch = CountDownLatch(1)

        activity.runOnUiThread {
            try {
                trusted.set(MainActivity.isTrustedAppUrl(webView.url))
            } finally {
                latch.countDown()
            }
        }

        return try {
            latch.await(2, TimeUnit.SECONDS) && trusted.get()
        } catch (_: InterruptedException) {
            Thread.currentThread().interrupt()
            false
        }
    }

    private fun showToast(message: String) {
        activity.runOnUiThread {
            Toast.makeText(activity, message, Toast.LENGTH_SHORT).show()
        }
    }
}
